#!/usr/bin/env perl

use 5.010;
use strict;
use autodie;
use warnings;

use Audio::XMMSClient;

$| = 1;

my $c = Audio::XMMSClient->new('xxxx');
$c->connect or die "Can't connect: " . $c->get_last_error . "\n";

my $r;

$r = $c->playback_current_id;
print_info($r->wait->value);

$r = $c->broadcast_playback_current_id;
$r->notifier_set(\&print_info);

$c->loop;

sub print_info {
	my $info = $c->medialib_get_info(shift)->wait->value;
	my @info = map {
		$info->{$_}->{'plugin/id3v2'} || ''
	} qw/artist album title/;

	my $command = <<EOC;
local naughty = require("naughty")
naughty.notify({
    preset = naughty.config.presets.normal,
    title = "$info[2]",
    text = "$info[0] - $info[1]",
	timeout = 5
})
EOC

	open my $awesome, '|-', '/usr/bin/awesome-client';
	print $awesome $command;
	close $awesome;
}



